name: ticket_visiting
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
     - images/
  fonts:
  - family: Fuggles,
    fonts:
      - asset: fonts/Fuggles-Regular.ttf

  - family: Kanit,
    fonts:
    - asset: fonts/Kanit-Regular.ttf


  - family: Pacifico,
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: SourceSans3-Regular,
    fonts:
    - asset: fonts/SourceSans3-Regular.ttf


  #fonts:
  #- family: Kanit-Regular,
  #  fonts:
  #   - asset: fonts/Kanit-Regular.ttf
  #     style: italic
  


  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
